namespace PasswordManager.MVVMApp.ViewModels
{
    public partial class MockVaultEntryViewModel : ViewModelBase
    {
        /// <summary>
        /// Initializes the class (created by the generator).
        /// </summary>
        static MockVaultEntryViewModel()
        {
            ClassConstructing();
            ClassConstructed();
        }
        /// <summary>
        /// This method is called before the construction of the class.
        /// </summary>
        static partial void ClassConstructing();
        /// <summary>
        /// This method is called when the class is constructed.
        /// </summary>
        static partial void ClassConstructed();

        /// <summary>
        /// Initializes a new instance of the <see cref="MockVaultEntryViewModel"/> class (created by the generator.)
        /// </summary>
        public MockVaultEntryViewModel()
        {
            Constructing();

            Constructed();
        }
        /// <summary>
        /// This method is called the object is being constraucted.
        /// </summary>
        partial void Constructing();
        /// <summary>
        /// This method is called when the object is constructed.
        /// </summary>
        partial void Constructed();

        /// <summary>
        /// Property 'Name' generated by the generator.
        /// </summary>
        public System.String Name
        {
            get
            {
                return Name;
            }
            set
            {
                Name = value;
                OnPropertyChanged();
            }
        }

        /// <summary>
        /// Property 'Url' generated by the generator.
        /// </summary>
        public System.String Url
        {
            get
            {
                return Url;
            }
            set
            {
                Url = value;
                OnPropertyChanged();
            }
        }

        /// <summary>
        /// Property 'UserName' generated by the generator.
        /// </summary>
        public System.String UserName
        {
            get
            {
                return UserName;
            }
            set
            {
                UserName = value;
                OnPropertyChanged();
            }
        }

        /// <summary>
        /// Property 'Email' generated by the generator.
        /// </summary>
        public System.String Email
        {
            get
            {
                return Email;
            }
            set
            {
                Email = value;
                OnPropertyChanged();
            }
        }

        /// <summary>
        /// Property 'Password' generated by the generator.
        /// </summary>
        public System.String Password
        {
            get
            {
                return Password;
            }
            set
            {
                Password = value;
                OnPropertyChanged();
            }
        }

        /// <summary>
        /// Property 'MockUserUserName' generated by the generator.
        /// </summary>
        public System.String MockUserUserName
        {
            get
            {
                return MockUserUserName;
            }
            set
            {
                MockUserUserName = value;
                OnPropertyChanged();
            }
        }

        /// <summary>
        /// Property 'CreatedAt' generated by the generator.
        /// </summary>
        public System.DateTime CreatedAt
        {
            get
            {
                return CreatedAt;
            }
            set
            {
                CreatedAt = value;
                OnPropertyChanged();
            }
        }

        /// <summary>
        /// Property 'ModifiedAt' generated by the generator.
        /// </summary>
        public System.DateTime ModifiedAt
        {
            get
            {
                return ModifiedAt;
            }
            set
            {
                ModifiedAt = value;
                OnPropertyChanged();
            }
        }
    }
}